---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
        # Replace $GCLOUD_PROJECT with your project ID.
        image: asia-east1-docker.pkg.dev/devops-project-419807/frontend/react_app:1.0
        #imagePullPolicy: Always
        # This app listens on port 8080 for web traffic by default.
        # ports:
        # - containerPort: 8080
        env:
          - name: PORT
            value: "3000"
          - name: REACT_APP_URL
            value: "http://backend:8080"
        resources:
          requests:
            memory: 256Mi
            cpu: "0.5"
          limits:
            memory: 512Mi
            cpu: "1"

            

          