---
apiVersion: v1
kind: Service
metadata:
  name: reactapp
spec:
  type: LoadBalancer
  selector:
    app: reactapp
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp
  labels:
    app: reactapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gke_reactapp
  template:
    metadata:
      labels:
        app: gke_reactapp
    spec:
      containers:
      - name: reactapp
        image: asia-east1-docker.pkg.dev/devops-project-419807/frontend/react_app:1.0